export const Icons = {
  rightArrow: require('../../../assets/icon/rightArrows.png'),
  diamond: require('../../../assets/icon/diamond.png'),
  coffeeBg: require('../../../assets/background/coffee2.webp'),
  cup: require('../../../assets/icon/cup.png'),
  upload: require('../../../assets/icon/upload.png'),
  message: require('../../../assets/icon/message.png'),
  user: require('../../../assets/icon/user.png'),
  edit: require('../../../assets/icon/edit.png'),
  password: require('../../../assets/icon/password.png'),
  token: require('../../../assets/icon/token.png'),
  info: require('../../../assets/icon/info.png'),
  logout: require('../../../assets/icon/logout.png'),
  rightChevron: require('../../../assets/icon/rightChevron.png'),
  save: require('../../../assets/icon/save.png'),
  left: require('../../../assets/icon/left.png'),
  hide: require('../../../assets/icon/hide.png'),
  show: require('../../../assets/icon/show.png'),
  plus: require('../../../assets/icon/plus.png'),
  translate: require('../../../assets/icon/translate.png'),
  accountSettings: require('../../../assets/icon/accountSettings.png'),
};
